parameter_defaults:
  NovaSchedulerDefaultFilters:
    - "RetryFilter"
    - "AvailabilityZoneFilter"
    - "ComputeFilter"
    - "ComputeCapabilitiesFilter"
    - "ImagePropertiesFilter"
    - "ServerGroupAntiAffinityFilter"
    - "ServerGroupAffinityFilter"
    - "PciPassthroughFilter"
    - "NUMATopologyFilter"
    - "AggregateInstanceExtraSpecsFilter"
  NovaSchedulerAvailableFilters: ["nova.scheduler.filters.all_filters","nova.scheduler.filters.pci_passthrough_filter.PciPassthroughFilter"]
  NeutronExternalNetworkBridge: "''"
  NeutronEnableIsolatedMetadata: true
  NeutronEnableForceMetadata: true
  NeutronTunnelTypes: ''
  NeutronOVSFirewallDriver: iptables_hybrid
  NeutronFlatNetworks:
    - management
    - external
  NeutronNetworkVLANRanges:
    - offload1:178:178
    - offload2:177:177
  NeutronBridgeMappings:
    - management:br-mgmt
    - external:br-mgm2

  #############################
  # OVS Offload configuration #
  #############################
  ComputeSriovRTExtraConfig:
    nova::compute::libvirt::libvirt_cpu_mode: 'host-passthrough'
    nova::compute::libvirt::libvirt_cpu_model_extra_flags: 'tsc-deadline'
    nova::compute::libvirt::libvirt_realtime_scheduler_priority: '1'
  ComputeSriovRTParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=70 iommu=pt intel_iommu=on isolcpus=12-35 mitigations=off nopti spectre_v2=off spec_store_bypass_disable=off l1tf=off kvm-intel.vmentry_l1d_flush=never clocksource=tsc powernow-k8.tscsync=1"
    TunedProfileName: "realtime-virtual-host"
    OvsHwOffload: True
    IsolCpusList: "12-35"
    NovaComputeCpuDedicatedSet: ['12-35']
    NovaReservedHostMemory: 4096
    NovaComputeCpuSharedSet: "0-11"
    ImageDefault: overcloud-realtime-compute
    NovaLibvirtMemStatsPeriodSeconds: 0
    NovaLibvirtRxQueueSize: 1024
    NovaLibvirtTxQueueSize: 1024
    NeutronBridgeMappings:
      - offload1:br-offload1
      - offload2:br-offload2
      - management:br-mgmt
      - external:br-mgmt2
    NeutronPhysicalDevMappings:
      - offload1:ens3f0
      - offload2:ens3f1
    NovaPCIPassthrough:
      - devname: "ens3f0"
        physical_network: "offload1"
      - devname: "ens3f1"
        physical_network: "offload2"
